spring:
  application:
    name: forbidden-words-service
  datasource:
    driverClassName: org.postgresql.Driver
#   url: jdbc:postgresql://db:5432/forbidden_service_db
    url: jdbc:postgresql://localhost:5432/forbidden_service_db
    password: root
    username: postgres
