server:
  port: 8888

spring:
  profiles:
    active: default
  application:
    name: config_server_application
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config-repo/

logging:
  level:
    org.springframework.cloud.config: DEBUG