server:
  port: 8888

spring:
  application:
    name: config_server_application
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo.git # или локальный путь
          clone-on-start: true
