spring:
  application:
    name: posts-service
  datasource:
    driverClassName: org.postgresql.Driver
    #   url: jdbc:postgresql://db:5432/post_service_db
    url: jdbc:postgresql://localhost:5432/post_service_db
    username: postgres
    password: root


  post:
    max:
      length: 25

